spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://user_service
          predicates:
            - Path=/users/**
        - id: notification_service
          uri: lb://notification_service
          predicates:
            - Path=/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/